# 主题
theme: jekyll-theme-cayman

# 网站信息
title: jmeter-dubbo-plugin
description: JMeter Dubbo 插件使用文档

# GitHub 跳转
github_url: https://github.com/solsynx/jmeter-dubbo-plugin

# 自定义域名
baseurl: ""
url: "https://jmeter-dubbo-plugin.solsynx.com"

# 正确写法！不要写 true
readme_index:
  enabled: true

# 插件
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

show_downloads: false
