<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.solsynx</groupId>
    <artifactId>jmeter-dubbo-plugin</artifactId>
    <version>0.0.6</version>
  </parent>

  <artifactId>jmeter-dubbo-zookeeper</artifactId>
  <packaging>jar</packaging>

  <name>JMeter Dubbo Plugin :: Registry Zookeeper</name>
  <description>Zookeeper registry support for JMeter Dubbo Plugin</description>

  <dependencies>
    <!-- Core module dependency -->
    <dependency>
      <groupId>com.solsynx</groupId>
      <artifactId>jmeter-dubbo-core</artifactId>
      <version>${project.version}</version>
    </dependency>

    <!-- Zookeeper dependencies for 3.4.x versions -->
    <dependency>
      <groupId>org.apache.curator</groupId>
      <artifactId>curator-x-discovery</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.zookeeper</groupId>
      <artifactId>zookeeper</artifactId>
    </dependency>

  </dependencies>

</project>
